version: '2'

services:
  master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/tmp/data

  jupyter:
    build:
      context: .
      dockerfile: jupyter.dockerfile
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 8888:8888
      - 8080
    user: root
    environment:
      MASTER: spark://master:7077
      PYSPARK_DRIVER_PYTHON: ipython
      PYSPARK_DRIVER_PYTHON_OPTS: 'notebook --ip=0.0.0.0 --no-browser --debug'
    command: /usr/local/spark-2.0.0-bin-hadoop2.6/bin/pyspark --master spark://master:7077
    #command: jupyter notebook --ip=0.0.0.0 --no-browser --debug
    #command: start-notebook.sh

  zeppelin:
    image: dylanmei/zeppelin
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=1g
        -Dspark.executor.memory=2g
        -Delasticsearch.host=elasticsearch
      SPARK_SUBMIT_OPTIONS: >-
        --conf spark.es.nodes.wan.only=true
        --conf spark.es.port=9200
      MASTER: spark://master:7077
    ports:
      - 7070:8080
    volumes:
      - ./notebooks:/usr/zeppelin/notebook

  worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/tmp/data
